# Generated by Django 3.1.1 on 2020-09-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersAndPayment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Details',
            new_name='Order_Detail',
        ),
    ]
